// Küratör seçkisi — tek doğruluk kaynağı (API rotası da buradan beslenir)
export const GAMES = [
  { id: 'gates', icon: '⚡', name: 'Gates of Olympus', cat: 'risk', rtp: '96.50', vol: 'Yüksek', type: 'slot',
    note: 'Geçen hafta Sweet Bonanza oynadın — benzer çarpan mekaniği, daha yüksek tavan.' },
  { id: 'mt4', icon: '🚂', name: 'Money Train 4', cat: 'risk', rtp: '96.10', vol: 'Yüksek', type: 'slot',
    note: 'Büyük turlar sabırlı oyuncuları sever; bonus avcısı profiline uygun.' },
  { id: 'wdw', icon: '🤠', name: 'Wanted Dead or a Wild', cat: 'risk', rtp: '96.38', vol: 'Yüksek', type: 'slot',
    note: 'Düello özelliği, adrenalin skorunla birebir eşleşiyor.' },
  { id: 'sp', icon: '✨', name: 'Starlight Princess', cat: 'calm', rtp: '96.50', vol: 'Orta-Düşük', type: 'slot',
    note: 'Uzun akşam seansların için yumuşak iniş çıkışlar.' },
  { id: 'sb', icon: '🍬', name: 'Sweet Bonanza', cat: 'calm', rtp: '96.48', vol: 'Orta', type: 'slot',
    note: 'Geçen ayın favorisi — Dürtü analizine göre bu hafta şansın burada.' },
  { id: 'bs', icon: '🦇', name: 'Blood Suckers', cat: 'calm', rtp: '98.00', vol: 'Düşük', type: 'slot',
    note: 'Seçkideki en yüksek RTP; bütçe dostu, uzun nefesli oyun.' },
  { id: 'aviator', icon: '✈️', name: 'Aviator', cat: 'adren', rtp: '97.00', vol: 'Crash', type: 'crash',
    note: 'Seçkideki tek crash oyunu — Dürtü bilinçli seçti.' },
  { id: 'plinko', icon: '🟢', name: 'Plinko Original', cat: 'orig', rtp: '99.00', vol: 'Ayarlanabilir', type: 'plinko',
    note: 'Çivi piramidinden süzülen toplar — 8-16 satır ve 1000× dev çarpan.' },
  { id: 'limbo', icon: '🚀', name: 'Limbo Rocket', cat: 'adren', rtp: '99.00', vol: 'Yüksek Tavan', type: 'limbo',
    note: 'Hedef çarpanını belirle, anında roketle — 10.000× limitli saf şans.' },
  { id: 'bj', icon: '🂡', name: 'VIP Blackjack Masası', cat: 'strat', rtp: '99.40', vol: 'Masa', type: 'table',
    note: 'Canlı kumaş masa, Split, Double Down ve Sigorta seçenekleriyle otantik deneyim.' },
  { id: 'rl', icon: '🎡', name: 'Avrupa Rulet Masası', cat: 'strat', rtp: '97.30', vol: 'Masa', type: 'roulette',
    note: 'Gerçek kumaş örtü üzerinde tam bahis yerleşimi, dönen çark ve bilye fiziği.' },
  { id: 'mines', icon: '💣', name: 'Mines Deluxe', cat: 'adren', rtp: '97.00', vol: 'Tarla', type: 'mines',
    note: '5×5 metal karo — artan basamaklı kristal sesleri ve dinamik elmas çarpanları.' },
  { id: 'hilo', icon: '🃏', name: 'Hi-Lo Yüksek/Düşük', cat: 'orig', rtp: '98.00', vol: 'Seri Strateji', type: 'hilo',
    note: 'Sonraki kart büyük mü küçük mü? Olasılıklar canlı hesaplanır, kazanç zinciri birikir.' },
  { id: 'wheel', icon: '🎯', name: 'Şans Çarkı (Wheel)', cat: 'orig', rtp: '98.50', vol: 'Çoklu Kademe', type: 'wheel',
    note: 'Özel segmentler, tıkırdayan ibre ve 50× çarpanlı çark deneyimi.' },
];

export const CATS = [
  ['all', 'Tümü'],
  ['orig', '💎 Orijinaller'],
  ['risk', '🎩 Yüksek Risk'],
  ['calm', '🍷 Uzun Akşam'],
  ['adren', '⚡ Adrenalin'],
  ['strat', '🎯 Stratejist'],
];
